### PR TITLE
Fixed issue with CloseHand() for ADA in sim 

### PR DESCRIPTION
**Pull request by Stefanos19**

### CODE REVIEW

**Comment by mkoval** [comment]
Note that `MoveHand` function ignores collisions and will always terminate with the hand fully closed, even if it is penetrating an object. The `robot.task_manipulation.CloseFingers()` function simulates closing the fingers until they are in collision. This is why we have separate functions for `CloseFingers` and `OpenFingers`.

**Comment by mkoval** [comment]
@Stefanos19 Can you take a look at my comment above?

**Comment by Stefanos19** [comment]
I think the issue is that the command:  robot.task_manipulation.prob.SendCommand('CloseFingers') returns the following error: 
[grasperplanner.cpp:258 PlanPath] no objects in environment

**Comment by mkoval** [comment]
I will merge this for now. However, it is really not correct - we should figure out why `CloseFinger`s is failing.

@Stefanos19 Please make an issue about this.

**Pull request merged**
