### PR TITLE
changed acceleration limits

### PR DESCRIPTION
**Pull request by Stefanos19**
ADA moves slightly faster after the Kinova firmware upgrade, while still having a high success-rate in grasping the bites in the ada-meal scenario demo.

### CODE REVIEW

**Comment by mkoval** [comment]
Please verify these in a controlled test before merging this; i.e. command the arm to go from zero velocity to maximum velocity instantaneously and see how fast it can accelerate.

**Comment by Stefanos19** [comment]
Ok sounds good.

**Comment by Stefanos19** [comment]
So, I verified the acceleration limits. I will set them to these values and make a new PR. 

j1
Acceleration limit: 1.4507

j2
Acceleration limit: 1.5633

j3
Acceleartion limit: 1.5596

j4
Acceleration limit; 1.4955

j5
Acceleartion limit: 1.4807

j6
Acceleration Limit: 1.4887

**Comment by mkoval** [comment]
LGTM. Thanks @Stefanos19!

**Pull request merged**
