### PR TITLE
Enabled ActiveDOFs in several planners

### PR DESCRIPTION
**Pull request by mkoval**
This commit sets the ActiveDOFs CollisionOption flag in: OMPL, SnapPlanner, VectorFieldPlanner, and GreedyIkPlanner.

### CODE REVIEW

**Comment by mkoval** [comment]
I noticed #319 while writing unit tests for CHOMP. If we resolve that issue, then we can also enable `PlanToConfigurationTestCollisionTest` on CHOMP.

**Comment by cdellin** [comment]
I added a temporary `printf` in `or_fcl`'s `FCLCollisionChecker::SetCollisionOptions` method.  Note on my machine that the enum value `OpenRAVE::CO_ActiveDOFs` has value `0x10` = `16`.

**CHOMP before/after:**
```
calling planning method ...
...
[orcdchomp_mod.cpp:2875 gettraj] timing trajectory ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
[orcdchomp_mod.cpp:2930 gettraj] checking trajectory for collision ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
```
calling planning method ...
...
RECEIVED OPTIONS 16 (env id 3)!
...
[orcdchomp_mod.cpp:2875 gettraj] timing trajectory ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
[orcdchomp_mod.cpp:2930 gettraj] checking trajectory for collision ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
(I'm not exactly sure what's going on here. During `timing trajectory`, the module does call `OpenRAVE::planningutils::RetimeActiveDOFTrajectory`, which I believe sets the `CO_ActiveDOFs` flag temporarily. But I'm not sure what the last pair calls in both the before and after case are.)

**OMPL_RRTConnect before/after:**
```
calling planning method ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
[RRTConnect.cpp:185] RRTConnect: Starting planning with 1 states already in datastructure
[RRTConnect.cpp:292] RRTConnect: Created 5 states (3 start + 2 goal)
[SimpleSetup.cpp:129] Solution found in 0.547832 seconds
RECEIVED OPTIONS 0 (env id 3)!
```
```
calling planning method ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
[RRTConnect.cpp:185] RRTConnect: Starting planning with 1 states already in datastructure
[RRTConnect.cpp:292] RRTConnect: Created 5 states (2 start + 3 goal)
[SimpleSetup.cpp:129] Solution found in 0.877408 seconds
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
(I'm not sure what the first two calls are in both before and after. `or_ompl` currently sets the `CO_ActiveDOFs` flag internally, and this PR introduces a second state saver around it, so the output otherwise makes senes.)

**Snap before/after:**
```
calling planning method ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
```
calling planning method ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
(Not sure about this one either.  Looks like there may be an inner state saver somewhere which enforces the flag to be off, and this PR adds a saver on the outside which turns it on.)

**Vectorfield before/after:**
```
calling planning method ...
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
```
calling planning method ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
(Same as Snap.)

**GreedyIK before/after:**
```
calling planning method ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
```
```
calling planning method ...
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 0 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
RECEIVED OPTIONS 16 (env id 3)!
No handlers could be found for logger "prpy.planning.workspace"
RECEIVED OPTIONS 0 (env id 3)!
```
(Don't ask me about this one!)

**Comment by mkoval** [comment]
@cdellin and I tracked down most of mystery `CollisionOptions` calls to `GetNonAdjacentLinks`. The only ones remaining are the repeated calls in `GreedyIk`, which likely come from the IK filter.

I am content with merging this pull request once @cdellin signs off on it.

**Comment by cdellin** [comment]
This looks good to me!

**Pull request merged**
