### PR TITLE
Feature: Custom prpy futures

### PR DESCRIPTION
**Pull request by psigen**
This PR adds custom futures (adapted from adapy) into prpy and uses them instead of Trollius for deferred planning and execution.

This PR is **not** ready for merge yet, this is for discussion and review.

### CODE REVIEW

**Comment by psigen** [comment]
@mkoval: What do we think?

**Comment by mkoval** [comment]
What's the status of this? Is this still true?:

> This PR is not ready for merge yet, this is for discussion and review.

**Comment by psigen** [comment]
Hmm, actually, I don't remember, looking over the PR it looks like it probably works, but maybe it doesn't handle all the metaplanners.

**Comment by psigen** [comment]
This PR is super busted.  Going to try to break it up into smaller steps.  First piece is here:
https://github.com/personalrobotics/prpy/pull/250

**Pull request closed without merging**
