### PR TITLE
Add minimal implementation of OptimizingPlannerSmoother (e.g. for chomp as a smoother)

### PR DESCRIPTION
**Pull request by cdellin**

### CODE REVIEW

**Comment by mkoval** [comment]
Looks good. You mentioned you had a test for this - could you commit it?

**Comment by cdellin** [comment]
I have a script that uses this one one problem, but it isn't yet self-contained or unittest-like.  I'll definitely commit it next time I work on this.  I the meantime, feel free to leave this unmerged if you want.

**Comment by mkoval** [comment]
Can you post the script somewhere? It should be pretty straightforward for me to write a few basic tests.

**Comment by cdellin** [comment]
I threw it on Trello last week ... also in this gist: https://gist.github.com/cdellin/b6ef2887f0d01f30581c

**Comment by cdellin** [comment]
Oh, just realized the problem definitions aren't in that file ... they're here:

https://github.com/cdellin/e8-papers/tree/master/e8_experiments/pypkgs/e8_experiments

**Comment by cdellin** [comment]
I updated the gist with the latest experimental script.  Here's how I'm calling the optimizer as a trajectory smoother:
```
smoother = prpy.planning.retimer.OptimizingPlannerSmoother(
   prpy.planning.chomp.CHOMPPlanner(),
   lambda_=20.0, n_iter=200,
   obs_factor=100.0, obs_factor_self=100.0)
traj_smoothed = smoother.RetimeTrajectory(robot, traj_orig)
```

Here's a video showing the result: https://www.youtube.com/watch?v=0k3bRxnjIlw

**Comment by psigen** [comment]
I have an `OptimizeTrajectory` method in `or_trajopt`.  How do I make that work with this?

**Comment by cdellin** [comment]
@psigen This smoother (`OptimizingPlannerSmoother`) is just a thin wrapper that implements `smoother.RetimeTrajectory()` by calling `planner.OptimizeTrajectory()` on a particular planner object that you construct and pass to it.  So you would do something like:
```
robot.smoother = prpy.planning.retimer.OptimizingPlannerSmoother(
    or_trajopt.planning.TrajoptPlanner())
```
The current problem with this is that the resulting trajectories often don't have sufficient timing information so that they can be executed on a physical robot.  We need to figure out the workflow for that.

**Comment by mkoval** [comment]
I am going to merge this before it falls further behind `master`.

**Pull request merged**
