### PR TITLE
Add support for numpy <1.8 which don't support norm(axis=1)

### PR DESCRIPTION
**Pull request by cdellin**
Numpy 1.8, released in October 2013, added an optional `axis` argument to `numpy.linalg.norm()`, which is used in prpy by `ik_ranking.py`.  My system uses an older version of Numpy, and I'd like it to be supported.  This PR does not change the code itself, but instead defines a custom function only when necessary which handles the axis case using the supported `numpy.apply_along_axis()` function.

### CODE REVIEW

**Comment by mkoval** [comment]
The change looks good.

However, part of me is inclined to say that you should upgrade NumPy. :smile:

**Comment by cdellin** [comment]
I am sympathetic to the suggestion that I upgrade Numpy (-: it'll just probably wait until after this whole PhD thing is done so I can upgrade to Jessie all at once.

**Comment by psigen** [comment]
Is this going to come up in other places?  Maybe it makes more sense to load a monkeypatch file like `prpy.compatibility.numpy` from  `prpy/__init__.py` that does this, so we can put together all the various numpy compatibility hacks one might need (e.g. `numpy.allclose`)

**Comment by mkoval** [comment]
:+1: Could you move this to a dedicated file?

**Comment by cdellin** [comment]
Done. For now I just added a file called compatibility.py.  If we end up with more of these, we can split it up into a compatibility module (although we can't name a file therein numpy.py, python gets very confused about that).

**Comment by psigen** [comment]
:+1: seems good to me.

**Comment by mkoval** [comment]
@jeking04 confirmed that this doesn't break anything on 14.04. (Thanks @jeking04!)

**Pull request merged**
