### PR TITLE
Fixed spurious CloneException errors in planning stack.

### PR DESCRIPTION
**Pull request by psigen**
Due to OpenRAVE weirdness, we are forced to throw a `CloneException` if a robot is cloned from a self-colliding configuration.  We also clone at the beginning of some of our planning operations.

This means that calling a planning method while a robot is in self-collision can create a `CloneException`, which is generally not expected or handled in code that is calling a planning method.  It is also not clear to calling code that this is actually a failure within a planner, and it breaks `MetaPlanner` logic.

In this PR, `ClonedPlanningMethod`s will catch `CloneException`s and wrap them as `ClonedPlanningError`s instead, which inherit from `PlanningError` and are thus handled correctly throughout the planning stack as a form of planning failure.

### CODE REVIEW

**Comment by mkoval** [comment]
I am concerned that letting meta-planners catch `CloneException` as a `PlanningError` will mask deeper issues. All `ClonedPlanningMethod`s will fail if the start configuration is in self-collision. There are only a handful of `LockedPlanningMethod`s, which are all fast heuristic planners, so it is unlikely that any non-trivial planning calls will succeed.

I'd rather fail fast by letting the `CloneException` bubble up to the user, instead of silently ignoring most of the motion planners in a `Sequence`. What is the motivation for this change in behavior?

**Comment by psigen** [comment]
The motivation for this is that _no one_ actually handles `CloneException` anywhere right now.  It's simply not something you expect to happen when making an opaque planning method call.

If I put the robot into collision, and tell it to plan to another place, I don't expect to have to catch a `CloneException` to determine that I gave it an invalid starting location.  I expect a `PlanningError`, because it failed to plan.

Note that the _only_ reason we can get a `CloneException` right now is a situation in which _no_ planner can succeed.  `LockedPlanningMethod`s are also going to fail.  So I see no reason that we shouldn't be handling it the same way as any other error that makes planning fail.

**Comment by mkoval** [comment]
I see your point. I was missing the obvious (in hindsight) fact that a `LockedPlanner` would also fail because *the robot starts in self-collision*. I will merge this once Travis is happy.

**Comment by psigen** [comment]
@mkoval bump.

**Comment by mkoval** [comment]
Travis is happy. Merging.

**Pull request merged**
