### PR TITLE
Bugfixes for SnapPlanner

### PR DESCRIPTION
**Pull request by mkoval**
I made the following changes:
1. Added the missing absolute value in our distance calculation (#16)
2. Removed the `snap_tolerance` parameter and, instead, use the DOF resolutions (#17)
3. Check collision at the start and end-points of the trajectory (#18)

I am holding off on merging the pull request until I do some more testing. It would also be good to get feedback from @siddhss5.

### CODE REVIEW

**Comment by mkoval** [comment]
I switched to collision checking the straight-line trajectory, instead of only allowing short snaps. Instead of implementing the collision detection manually, I call the built-in `CheckPathAllConstraints` function. This is the same function that built-in OpenRAVE planners (e.g. BiRRT) use to collision check edges. I am not sure whether that function does a bisection test or not.

I also added a few unit tests. [The test](https://github.com/personalrobotics/prpy/blob/bugfix/SnapPlanner/tests/test_SnapPlanner.py#L120) that checks self-collisions fails. This is quite surprising, because [a nearly identical test](https://github.com/personalrobotics/prpy/blob/bugfix/SnapPlanner/tests/test_SnapPlanner.py#L108) that checks environment collisions passes.

I haven't been able to figure out why. The logic inside `CheckPathAllConstraints` is incredibly complicated:

1. `CheckPathAllConstraints` [calls `_checkpathvelocityconstraintsfn`](https://github.com/rdiankov/openrave/blob/7d0dc9c945bab4fc6e3a703f707bb64656b7b897/include/openrave/planner.h#L238) on the `PlannerParameters` struct
2. The filter options are set to `0xFFFF` by default, which includes: ([see here](https://github.com/rdiankov/openrave/blob/7d0dc9c945bab4fc6e3a703f707bb64656b7b897/include/openrave/planner.h#L30))
    * `CFO_CheckEnvCollisions`
    * `CFO_CheckSelfCollisions`
    * `CFO_CheckTimeBasedConstraints`
    * `CFO_BreakOnFirstValidation`
2. `_checkpathvelocityconstraintsfn` [defaults to `DynamicsCollisionConstraint::Check`](https://github.com/rdiankov/openrave/blob/8e2ac09a4c91e63c34c0a01e675ebe38f78de6d0/src/libopenrave/planner.cpp#L441)
3. [`DynamicsCollisionConstraint::Check`](https://github.com/rdiankov/openrave/blob/2f7c8a6e582fd74746902e63b5707052fee87b09/src/libopenrave/planningutils.cpp#L2122) checks both geometric and dynamic feasibility
    * Passing empty vectors for `dq0` and `dq1` seems to disable checks for dynamic feasibility ([this case](https://github.com/rdiankov/openrave/blob/2f7c8a6e582fd74746902e63b5707052fee87b09/src/libopenrave/planningutils.cpp#L2339))
    * There is a suspicious comment that says "this does not check the end config, and may or may not check the start based on the value of 'start'"
4. `Check` calls the [`_SetAndCheckState` function](https://github.com/rdiankov/openrave/blob/2f7c8a6e582fd74746902e63b5707052fee87b09/src/libopenrave/planningutils.cpp#L1982), which sets the robot's configuration
5. `_SetAndCheckState` calls the [`_CheckState` function](https://github.com/rdiankov/openrave/blob/2f7c8a6e582fd74746902e63b5707052fee87b09/src/libopenrave/planningutils.cpp#L2020) to actually do the collision checking

I haven't been able to figure out where in this labyrinth is amiss.

@psigen @siddhss5 @cdellin: Any suggestions?

**Comment by siddhss5** [comment]
Yikes! You're not going to like this but I'd suggest we get some 'ground truth' by writing a simple line segment checker on our own, maybe even with just increments.

I was thinking it might be nice to write out the 'checkOrder' function as a generator allowing us explore different orders.

Sidd.

(Rapidly written in motion)

**Comment by mkoval** [comment]
It turns out that `CheckPathAllConstraints` works fine. There is a more fundamental issue here: `CheckSelfCollision` returns `True` in the original environment, but `False` in the cloned environment. Both environments look identical in the viewer, so this seems to be some sort of cloning issue.

**Comment by mkoval** [comment]
It gets even weirder. This test case works: 808b55ad86b09ded4837bfcda66e8d9eefc82494.

**Comment by mkoval** [comment]
I opened an OpenRAVE issue: https://github.com/rdiankov/openrave/issues/335. I'm out of ideas here, so hopefully Rosen can point us in the right direction.

**Comment by siddhss5** [comment]
My guess is that the clone is somehow mangling the adjacency list and skipping some/all link pair collision checks. Does 'verbose' print out enough info to verify this? Or maybe the collision report?

Sidd.

(Rapidly written in motion)

**Comment by mkoval** [comment]
Nope. `CheckSelfCollision` immediately returns false without any logging. It also doesn't fill in the `CollisionReport`.

Rosen thinks this is related to the assumption that initial configuration of the robot (by default: the zero configuration) is not in self collision. This is used to initialize the adjacency list when loading the robot. I had the same idea, but `GetAdjacentLinks()` returns the same values before and after cloning.

**Pull request merged**
